Training pipelines for Sparseconvunet
intel-isl/Open3D-ML pull request #233
Opened 2021-03-04 10:55 UTC by sanskar107

Added torch and tensorflow training pipelines for SparseConvUnet.

2021-04-28 17:59 UTC, ssheorey requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/233)* status: 0 of 16 files reviewed, 48 unresolved discussions (waiting on @sanskar107)

___
*[ml3d/configs/sparseconvunet_scannet.yml, line 14 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQT7Sx5xW_yQiysmBY:-MYQT7Sx5xW_yQiysmBZ:bu1o28a) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L14)):*
> ```YAML
>   batcher: ConcatBatcher
>   ckpt_path: # path/to/your/checkpoint
>   m: 32
> ```

Can we use a more descriptive name?
___
*[ml3d/configs/sparseconvunet_scannet.yml, line 28 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQTM2K7pvhwcSkveTI:-MYQTM2K7pvhwcSkveTJ:bry6got) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L28)):*
> ```YAML
>       max_s: 1.1
>     noise:
>       noise_level: 0.01
> ```

Is this Gaussian noise \sigma? Can we rename to `noise_std` or `noise_sigma`?
___
*[ml3d/configs/sparseconvunet_scannet.yml, line 39 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQWlYm9bj56HwelAaL:-MYQWlYm9bj56HwelAaM:bu8b4cz) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L39)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>     ChromaticAutoContrast:
>       randomize_blend_factor: True
>       blend_factor: 0.5
>     ChromaticTranslation:
>       trans_range_ratio: 0.1
>     ChromaticJitter:
>       std: 0.05
> ```
</details>

Can we document these augmentation methods and parameters? e.g.: `See ml3d/datasets/augment/augmentation.py` for details...
___
*[ml3d/configs/sparseconvunet_scannet.yml, line 44 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQU_D9BUOu4RA6Nhfr:-MYQU_D9BUOu4RA6Nhfs:brvlnel) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L44)):*
> ```
>   adam_lr: 0.001
>   batch_size: 8
>   learning_rate: 0.01
> ```
Is learning rate duplicated? Can we structure this more clearly?
Also, we have `adam_lr` in some configs and
```
optimizer:
    lr: 0.001
    betas: [0.95, 0.99]
    weight_decay: 0.01
```
in others. I prefer the 2nd form since it groups all optimizer parameters together. We can make the parameters subkeys (e.g. `optimizer.adam.lr`) if needed. In general, lets try to match the parameter names with the argument names in the PyTorch / TF function, so that users can easily find docs on these parameters.
___
*[ml3d/datasets/augment/augmentation.py, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYfmp5_1Vtal0CRpWqu:-MYfmp5_1Vtal0CRpWqv:b95s161) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L1)):*
> ```Python
> import numpy as np
> ```

General comments:
- Many augmentation methods (rotate, scale, noise, flip, etc.) should be useful for multiple pipelines, so we can put them in a base class (say `Augmentation`) and have `SemSegAugmentation` and `ObjdetAugmentation` inherit from it.
- All of these methods need documentation. The goal should be to have documentation at a level similar to libraries such as PyTorch / TensorFlow. We are following the Google style guide in the main repo for Python documentation.
- Let's add error checking for the user supplied config. Currently, if the user makes a spelling mistake (e.g.: 'Liner' normalization method instead of 'linear', these functions will silently do nothing. `if ... else if ... else if ... else raise ValueError('Unsupported option {}')` should give meaningful error messages.
- Random numbers: Let's consistently use the same RNG - either Python or Numpy. They use different algorithms internally, so Python will not honor Numpy seed settings and vice versa for deterministic results. [Numpy looks more convenient]. 
___
*[ml3d/datasets/augment/augmentation.py, line 14 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOH70f9wMlCRNaXEA-:-MZOH70f9wMlCRNaXEA0:b-13quot) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L14)):*
> ```
>         if 'points' in cfg.keys():
> ```
For checking for presence in a dict or iterating over a dict, do not use `keys()`. `if 'points' in cfg:` is prefereable.
https://google.github.io/styleguide/pyguide.html
___
*[ml3d/datasets/augment/augmentation.py, line 22 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOH_wv2PaO_y0h--DX:-MYfkosA57GZAuNoQHYY:b-lo25zy) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L22)):*
> ```Python
>                 pc /= (pc.max(0) - pc.min(0)).max()
> 
>         if 'feat' in cfg.keys() and feat is not None:
> ```

remove `keys()`
___
*[ml3d/datasets/augment/augmentation.py, line 72 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYfz8sB-NEcSztVE1XY:-MYfz8sB-NEcSztVE1XZ:by3v988) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L72)):*
> ```Python
> 
>     @staticmethod
>     def scale(pc, cfg):
> ```

Does this need re-centering before applying scaling? Probably a good idea to make this explicit if we are relying this.
___
*[ml3d/datasets/augment/augmentation.py, line 88 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYfzFxH1ekLULoxYnw0:-MYfzFxH1ekLULoxYnw1:b-centow) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L88)):*
> ```Python
>     @staticmethod
>     def noise(pc, cfg):
>         noise_level = cfg.get('noise_level', 0.001)
> ```

`noise_level` -> `noise_sigma` or `noise_std`
___
*[ml3d/datasets/augment/augmentation.py, line 125 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYg19moEJUbLoytGEEx:-MYg19moEJUbLoytGEEy:b-bjevh4) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L125)):*
> ```Python
> 
>             assert hi.max(
>             ) > 1, "Invalid color value. Color is supposed to be in [0-255] for ChromaticAutoContrast augmentation"
> ```

Error message should be `[0,1] instead of [0-255]`, since we are comparing with 1
___
*[ml3d/datasets/augment/augmentation.py, line 155 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOHzHt0sK7hBUsEkLy:-MYg2kyE-iPFqcI7wnD1:b6xbl8k) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L155)):*
> ```Python
>         return feats
> 
>     def augment(self, point, feat, labels, cfg):
> ```

Can you add documentation about any constraints on the augmentation operations?. e,g. normalize must be done before scale, so cannot use scale without normalize and so on.
___
*[ml3d/datasets/augment/augmentation.py, line 159 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYg2L1j3Q-Cp8lUUXNZ:-MYg2L1j3Q-Cp8lUUXN_:bq64ydu) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L159)):*
> ```Python
>             return point, feat, labels
> 
>         if 'normalize' in cfg.keys():
> ```

remove `keys()` here and below as well
___
*[ml3d/tf/dataloaders/tf_dataloader.py, line 172 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOJbLO-nFCsQRGyoWb:-MZOJbLO-nFCsQRGyoWc:b-lo25zy) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/dataloaders/tf_dataloader.py#L172)):*
> ```Python
>                 num_parallel_calls=tf.data.experimental.AUTO [...]

2021-04-30 14:01 UTC, sanskar107 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/233)* status: 0 of 16 files reviewed, 48 unresolved discussions (waiting on @sanskar107 and @ssheorey)

___
*[ml3d/configs/sparseconvunet_scannet.yml, line 14 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQT7Sx5xW_yQiysmBY:-MZY3KpB1oNumt165Y43:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L14)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can we use a more descriptive name?
</blockquote></details>

Done.
___
*[ml3d/configs/sparseconvunet_scannet.yml, line 28 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQTM2K7pvhwcSkveTI:-MZY3Lpi20kfa7bWWKLB:bkq5man) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L28)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Is this Gaussian noise \sigma? Can we rename to `noise_std` or `noise_sigma`?
</blockquote></details>

Yes, this scales down the normal distribution. Done.
___
*[ml3d/datasets/augment/augmentation.py, line 14 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOH70f9wMlCRNaXEA-:-MZY3WY7AAmnxcgSOTfR:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L14)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>         if 'points' in cfg.keys():
> ```
For checking for presence in a dict or iterating over a dict, do not use `keys()`. `if 'points' in cfg:` is prefereable.
https://google.github.io/styleguide/pyguide.html
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 22 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOH_wv2PaO_y0h--DX:-MZY3XFwBVWQR-YX7AAL:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L22)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

remove `keys()`
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 88 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYfzFxH1ekLULoxYnw0:-MZY3Yhj3zSo5LtQ3kS_:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L88)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

`noise_level` -> `noise_sigma` or `noise_std`
</blockquote></details>

Done.
___
*[ml3d/datasets/augment/augmentation.py, line 125 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYg19moEJUbLoytGEEx:-MZY3ZZu1sM_VPkDizww:b-8xg31k) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L125)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Error message should be `[0,1] instead of [0-255]`, since we are comparing with 1
</blockquote></details>

We are asserting max value to be greater than 1. That means color should be in [0-255].
___
*[ml3d/datasets/augment/augmentation.py, line 159 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYg2L1j3Q-Cp8lUUXNZ:-MZY3kVi3BrF57FNtILx:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L159)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

remove `keys()` here and below as well
</blockquote></details>

Done.
___
*[ml3d/tf/dataloaders/tf_dataloader.py, line 172 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOJbLO-nFCsQRGyoWb:-MZY3n5U5Qvn2lDDyplK:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/dataloaders/tf_dataloader.py#L172)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

remove `keys()`
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 20 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOJxiqATXoXIuQ-yH5:-MZY3ne90_J7TgBcOS5Z:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L20)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

rename to `conv_block_reps` for clarity
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 37 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOKfCk56Tq7u7cLqc9:-MZY3nyi4ssXAo0Tugn9:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L37)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Use full names for clarity: `self.input_layer`, `self.sub_sparse_conv`, `self.batch_norm`, etc.
Also use nouns as names for objects / classes and verbs for function names.
`self.augment` -> `self.augmenter`.
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 101 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOMA6tD7d1ksyGhBgv:-MZY3oSN1v1WELfOfcSJ:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L101)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Add comments / names for magic constants (127.5, 4096, 0.001) to explain what's happening here.
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 197 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZONNpf2QQdgdWgIRAb:-MZY3pjZ-PQfDBfmNaUH:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L197)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>         Runs the loss on outputs of the model
>         :param outputs: logits
>         :param labels: labels
>         :return: loss
> ```
Use Google sphinx style for documentation. docstring should be in rst format.
https://google.github.io/styleguide/pyguide.html#381-docstrings
Examples: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 201 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOOKyl0Cox-l8-ufki:-MZY3q3e8FwaoM4FyVrw:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L201)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Remove extra blank lines
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 221 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOPALA6kJfZCclqn4T:-MZY3qwu8FSLurTB4lLS:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L221)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>         self.bn 
> ```
`self.batch_norm`
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 283 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOQT8s22V0KexW1VdL:-MZY3rJHCD4glUXhxtjn:b-896fix) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L283)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Clarify name. rev = ?
</blockquote></details>

Done.
___
*[ml3d/tf/models/sparseconvnet.py, line 290 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOQVjiCbhS5X60P_lt:-MZY3re7EnQm3cPE5WVW:b-896fix) ([raw file](ht [...]

2021-04-30 15:56 UTC, sanskar107 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/233)* status: 0 of 16 files reviewed, 48 unresolved discussions (waiting on @sanskar107 and @ssheorey)

___
*[ml3d/configs/sparseconvunet_scannet.yml, line 39 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQWlYm9bj56HwelAaL:-MZYL__n7uEP2Z17S0-z:b-v53fte) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L39)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>     ChromaticAutoContrast:
>       randomize_blend_factor: True
>       blend_factor: 0.5
>     ChromaticTranslation:
>       trans_range_ratio: 0.1
>     ChromaticJitter:
>       std: 0.05
> ```
Can we document these augmentation methods and parameters? e.g.: `See ml3d/datasets/augment/augmentation.py` for details...
</blockquote></details>

TODO: Separate PR
___
*[ml3d/configs/sparseconvunet_scannet.yml, line 44 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYQU_D9BUOu4RA6Nhfr:-MZYLgUi9FgJmCBsE9a3:b-k6fux3) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/configs/sparseconvunet_scannet.yml#L44)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>   adam_lr: 0.001
>   batch_size: 8
>   learning_rate: 0.01
> ```
Is learning rate duplicated? Can we structure this more clearly?
Also, we have `adam_lr` in some configs and
```
optimizer:
    lr: 0.001
    betas: [0.95, 0.99]
    weight_decay: 0.01
```
in others. I prefer the 2nd form since it groups all optimizer parameters together. We can make the parameters subkeys (e.g. `optimizer.adam.lr`) if needed. In general, lets try to match the parameter names with the argument names in the PyTorch / TF function, so that users can easily find docs on these parameters.


</blockquote></details>

I'll do this in a separate PR. We have to change this across all the previous models and test them.
___
*[ml3d/datasets/augment/augmentation.py, line 1 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MYfmp5_1Vtal0CRpWqu:-MZYLohBCERzHFYzHDId:b-v53fte) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L1)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

General comments:
- Many augmentation methods (rotate, scale, noise, flip, etc.) should be useful for multiple pipelines, so we can put them in a base class (say `Augmentation`) and have `SemSegAugmentation` and `ObjdetAugmentation` inherit from it.
- All of these methods need documentation. The goal should be to have documentation at a level similar to libraries such as PyTorch / TensorFlow. We are following the Google style guide in the main repo for Python documentation.
- Let's add error checking for the user supplied config. Currently, if the user makes a spelling mistake (e.g.: 'Liner' normalization method instead of 'linear', these functions will silently do nothing. `if ... else if ... else if ... else raise ValueError('Unsupported option {}')` should give meaningful error messages.
- Random numbers: Let's consistently use the same RNG - either Python or Numpy. They use different algorithms internally, so Python will not honor Numpy seed settings and vice versa for deterministic results. [Numpy looks more convenient]. 
</blockquote></details>

TODO: Separate PR
___
*[ml3d/datasets/augment/augmentation.py, line 155 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOHzHt0sK7hBUsEkLy:-MZYNbMO5tlparcvhfHi:bt1m5ds) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/datasets/augment/augmentation.py#L155)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Can you add documentation about any constraints on the augmentation operations?. e,g. normalize must be done before scale, so cannot use scale without normalize and so on.
</blockquote></details>

TODO: Separate PR.
___
*[ml3d/tf/models/sparseconvnet.py, line 128 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOMmOz6Z2VLjE6EpwF:-MZYNfgp81y_9FCbh9yM:bu4ab49) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L128)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> get_batch_gen
> ```
`get_batch_generator`
</blockquote></details>

This also affects multiple models. I'll address in a separate PR.
___
*[ml3d/tf/models/sparseconvnet.py, line 130 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOMtdmDaI5Gd-RzyIt:-MZYNl495apqYW9XtQjT:bj8bld6) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L130)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> concat_batch_gen
> ```
concat_batch_generator
</blockquote></details>

same as above.
___
*[ml3d/tf/models/sparseconvnet.py, line 208 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOOXad67Ec01IeqUaB:-MZYNmfD9tHwjoZHzeGz:b-eev6uk) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L208)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
> optimizer = tf.keras.optimizers.Adam(learning_rate=cfg_pipeline.adam_lr)
> ```
```
optimizer = tf.keras.optimizers.Adam(**cfg_pipeline.adam)
```
is more general and clear if we have this structure in the config file:
```
pipeline:
  - adam:
     - learning_rate: 0.001  
```
</blockquote></details>

Separate PR.
___
*[ml3d/tf/models/sparseconvnet.py, line 652 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOV2i68HWIaJVqGTt3:-MZYUE1D1prI1pv1TXQI:b-a2lh5r) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L652)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

> ```
>             elif isinstance(module, ReLUBlock):
>                 feat_list = module(feat_list)
>             elif module.__name__() == "ResidualBlock":
> ```
This conditional block (`isinstance` or `__name__` checking is rather messy. Can we replace this with function overloading? Perhaps for a subset of the conditions?
</blockquote></details>

I looked into this. We can overload methods using function decorators if the arguments (number/type) are different. But in this case, method itself is different and is getting called for same arguments. Do you have something in mind that would work?
___
*[ml3d/torch/models/sparseconvnet.py, line 165 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOZWPd30ZgtjRCUN1t:-MZYL1-xCjeQrdJpft9m:b57vqnd) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/torch/models/sparseconvnet.py#L165)):*
<details><summary><i>Previously, ssheorey wrote…</i></summary><blockquote>

Try to match yaml config parameter names with PyTorch / TF function argument names. See  comment in the TF version. This will let users more easily refer PyTorch / TF documentation for argument documentation.
</blockquote></details>

The main problem is that we have same config for torch and tf, and most of the argument names in torch and tf are different. e.g. (`learning_rate` in tf, `lr` in torch, `epsilon` in tf, `eps` in torch)


<!-- Sent from Reviewable.io -->

2021-05-05 17:28 UTC, ssheorey requested changes
> *[Reviewable](https://reviewable.io/reviews/intel-isl/open3d-ml/233)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @sanskar107)

___
*[ml3d/tf/models/sparseconvnet.py, line 614 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOTZCQAv8yz48waeC1:-MZxRXdJCkoIHaM-aVaT:b-8vo42f) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L614)):*
<details><summary><i>Previously, sanskar107 (Sanskar Agrawal) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rename m->network or layers or ....
___
*[ml3d/tf/models/sparseconvnet.py, line 652 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOV2i68HWIaJVqGTt3:-MZxRzv99VvV3BnUJPxv:by39q9v) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/tf/models/sparseconvnet.py#L652)):*
<details><summary><i>Previously, sanskar107 (Sanskar Agrawal) wrote…</i></summary><blockquote>

I looked into this. We can overload methods using function decorators if the arguments (number/type) are different. But in this case, method itself is different and is getting called for same arguments. Do you have something in mind that would work?
</blockquote></details>

I had something like this in mind. Let me know if it will work in this case:
All modules derive from a base module:

```
class UNetBlock(tf.keras.layers.Layer, ABC):
    """New abstract base class for UNet blcoks"""

    @abstractmethod
   def call(self, **kwargs):
       """Uniform call signature with kwargs for all blocks"""
       return updated_kwargs_dict_for_next_module


class ResidualBlock(UNetBlock):

    def call(self, **kwargs):
        # Throws exception if required kwarg is absent, ignores extra kwargs
       return updated_kwargs_dict_for_next_module


UNetBlock.register(ResidualBlock)

class UNet(tf.keras.layers.Layer):

    def call(self, pos_list, feat_list, training):
        # Construct exhaustive arguments for all UNetblocks as dict, say feat_list
        for module in self.net:
            feat_list = module(**feat_list)
```
___
*[ml3d/torch/models/sparseconvnet.py, line 165 at r1](https://reviewable.io/reviews/intel-isl/open3d-ml/233#-MZOZWPd30ZgtjRCUN1t:-MZxYWFoBnS_8JuEot7D:b-3rpu02) ([raw file](https://github.com/intel-isl/open3d-ml/blob/c08037970accb1bffa3fdf6c343ded67d6ab0a5e/ml3d/torch/models/sparseconvnet.py#L165)):*
<details><summary><i>Previously, sanskar107 (Sanskar Agrawal) wrote…</i></summary><blockquote>

The main problem is that we have same config for torch and tf, and most of the argument names in torch and tf are different. e.g. (`learning_rate` in tf, `lr` in torch, `epsilon` in tf, `eps` in torch)
</blockquote></details>

Let's go with the torch names, since we start working with PyTorch. We can maintain a dict of name translations in the TF code and just update the dict obtained from YAML before using it. This may affect all models, so OK to do in a separate PR.


<!-- Sent from Reviewable.io -->

2021-05-11 09:18 UTC, merged